### ISSUE TITLE
node 18 support

### ISSUE THREAD

**Issue by p-desaintchamas** [pmowrer/semantic-release-monorepo#135]
Hello, I'm using semantic-release-monorepo and I've been trying to bump the versions of semantic-release to 20.0, which is ESM only (not on the packages themselves, only for the semantic-release code itself. 

It seems the dependency to semantic-release-plugin-decorator is broken, as the package is no longer maintained, and this error is raised.

```
Error [ERR_REQUIRE_ESM]: require() of ES Module /builds/monorepo/node_modules/@semantic-release/gitlab/index.js from /builds/monorepo/node_modules/semantic-release-plugin-decorators/src/wrapStep.js not supported.
```

The dependency being very small & unmaintained, & the change quite minor it seems, would it be acceptable to merge it in the repo ?

**Comment by w4rlock** [comment]
My pull-request with support for node 18... is pending 
https://github.com/pmowrer/semantic-release-monorepo/pull/137

**Comment by JOU-amjs** [comment]
@w4rlock is merged?

**Comment by mario-jerkovic** [comment]
@p-desaintchamas  @JOU-amjs @w4rlock 
We've released a monorepo package that's compatible with ESM, and since you have access to the source code, you're free to customize it as you wish. Cheers! 🍻

**NPM package:** https://www.npmjs.com/package/@rimac-technology/semantic-release-monorepo
**Source code:** https://github.com/RimacTechnology/semantic-release-monorepo
