### ISSUE TITLE
Missing name in console output

### ISSUE THREAD

**Issue by snebjorn** [pmowrer/semantic-release-monorepo#86]
I see a bunch of these `[Function: ]`
```posh
[4:39:33 PM] [semantic-release] [[Function: ]] » i  The commit should not trigger a release
```
Shouldn't that show the plugin name?

Like
```posh
[4:42:03 PM] [semantic-release] [@semantic-release/github] » i  Verify GitHub authentication
```

**Comment by pmowrer** [comment]
It should, but I believe this is an unfortunate side-effect of the monkey patching necessary to make this library work. Instead of passing plugin names (strings that can be printed) to `semantic-release`, we have to wrap all plugins in a wrapper function (which is why you're seeing [`Function:`, I think).

**Comment by pmowrer** [comment]
I made an improvement here where at least it should say `semantic-release-monorepo` instead of anonymous function.
